/* Generated By:JavaCC: Do not edit this line. IrisParserConstants.java */
package com.irisine.jiris.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IrisParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNCTION = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int MODULE = 13;
  /** RegularExpression Id. */
  int INTERFACE = 14;
  /** RegularExpression Id. */
  int EXTENDS = 15;
  /** RegularExpression Id. */
  int INVOLVES = 16;
  /** RegularExpression Id. */
  int JOINTS = 17;
  /** RegularExpression Id. */
  int PERSONAL = 18;
  /** RegularExpression Id. */
  int RELATIVE = 19;
  /** RegularExpression Id. */
  int EVERYONE = 20;
  /** RegularExpression Id. */
  int GET = 21;
  /** RegularExpression Id. */
  int SET = 22;
  /** RegularExpression Id. */
  int GSET = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int ELSEIF = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int IN = 28;
  /** RegularExpression Id. */
  int SWITCH = 29;
  /** RegularExpression Id. */
  int WHEN = 30;
  /** RegularExpression Id. */
  int CAST = 31;
  /** RegularExpression Id. */
  int ITERATOR = 32;
  /** RegularExpression Id. */
  int SUPER = 33;
  /** RegularExpression Id. */
  int BREAK = 34;
  /** RegularExpression Id. */
  int CONTINUE = 35;
  /** RegularExpression Id. */
  int RETURN = 36;
  /** RegularExpression Id. */
  int BLOCK = 37;
  /** RegularExpression Id. */
  int SELF = 38;
  /** RegularExpression Id. */
  int WITH = 39;
  /** RegularExpression Id. */
  int WITHOUT = 40;
  /** RegularExpression Id. */
  int ORDER = 41;
  /** RegularExpression Id. */
  int SERVE = 42;
  /** RegularExpression Id. */
  int IGNORE = 43;
  /** RegularExpression Id. */
  int GROAN = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int FALSE = 46;
  /** RegularExpression Id. */
  int NIL = 47;
  /** RegularExpression Id. */
  int ALIAS = 48;
  /** RegularExpression Id. */
  int RETRY = 49;
  /** RegularExpression Id. */
  int REDO = 50;
  /** RegularExpression Id. */
  int GOTO = 51;
  /** RegularExpression Id. */
  int DOT = 52;
  /** RegularExpression Id. */
  int LP = 53;
  /** RegularExpression Id. */
  int RP = 54;
  /** RegularExpression Id. */
  int LC = 55;
  /** RegularExpression Id. */
  int RC = 56;
  /** RegularExpression Id. */
  int LB = 57;
  /** RegularExpression Id. */
  int RB = 58;
  /** RegularExpression Id. */
  int SEMICOLON = 59;
  /** RegularExpression Id. */
  int COMMA = 60;
  /** RegularExpression Id. */
  int LOGICAL_AND = 61;
  /** RegularExpression Id. */
  int LOGICAL_OR = 62;
  /** RegularExpression Id. */
  int LOGICAL_NOT = 63;
  /** RegularExpression Id. */
  int ASSIGN = 64;
  /** RegularExpression Id. */
  int EQ = 65;
  /** RegularExpression Id. */
  int NE = 66;
  /** RegularExpression Id. */
  int GT = 67;
  /** RegularExpression Id. */
  int GE = 68;
  /** RegularExpression Id. */
  int LT = 69;
  /** RegularExpression Id. */
  int LE = 70;
  /** RegularExpression Id. */
  int ADD = 71;
  /** RegularExpression Id. */
  int SUB = 72;
  /** RegularExpression Id. */
  int MUL = 73;
  /** RegularExpression Id. */
  int DIV = 74;
  /** RegularExpression Id. */
  int MOD = 75;
  /** RegularExpression Id. */
  int POWER = 76;
  /** RegularExpression Id. */
  int BIT_AND = 77;
  /** RegularExpression Id. */
  int BIT_OR = 78;
  /** RegularExpression Id. */
  int BIT_XOR = 79;
  /** RegularExpression Id. */
  int BIT_NOT = 80;
  /** RegularExpression Id. */
  int ASSIGN_ADD = 81;
  /** RegularExpression Id. */
  int ASSIGN_SUB = 82;
  /** RegularExpression Id. */
  int ASSIGN_MUL = 83;
  /** RegularExpression Id. */
  int ASSIGN_DIV = 84;
  /** RegularExpression Id. */
  int ASSIGN_MOD = 85;
  /** RegularExpression Id. */
  int ASSIGN_BIT_AND = 86;
  /** RegularExpression Id. */
  int ASSIGN_BIT_OR = 87;
  /** RegularExpression Id. */
  int ASSIGN_BIT_XOR = 88;
  /** RegularExpression Id. */
  int BIT_SHR = 89;
  /** RegularExpression Id. */
  int BIT_SHL = 90;
  /** RegularExpression Id. */
  int BIT_SAR = 91;
  /** RegularExpression Id. */
  int BIT_SAL = 92;
  /** RegularExpression Id. */
  int ASSIGN_BIT_SHR = 93;
  /** RegularExpression Id. */
  int ASSIGN_BIT_SHL = 94;
  /** RegularExpression Id. */
  int ASSIGN_BIT_SAR = 95;
  /** RegularExpression Id. */
  int ASSIGN_BIT_SAL = 96;
  /** RegularExpression Id. */
  int ITER = 97;
  /** RegularExpression Id. */
  int FILED = 98;
  /** RegularExpression Id. */
  int SHARP = 99;
  /** RegularExpression Id. */
  int CONLON = 100;
  /** RegularExpression Id. */
  int CONSTANCE = 101;
  /** RegularExpression Id. */
  int LOCALVARIABLE = 102;
  /** RegularExpression Id. */
  int GLOBALVARIABLE = 103;
  /** RegularExpression Id. */
  int INSTANCEVARIABLE = 104;
  /** RegularExpression Id. */
  int CLASSVARIABLE = 105;
  /** RegularExpression Id. */
  int UPPERLETTER = 106;
  /** RegularExpression Id. */
  int DOWNERLETTER = 107;
  /** RegularExpression Id. */
  int LETTER = 108;
  /** RegularExpression Id. */
  int DIGIT = 109;
  /** RegularExpression Id. */
  int LEAGLELETTER = 110;
  /** RegularExpression Id. */
  int INTEGER = 111;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 112;
  /** RegularExpression Id. */
  int HEX_LITERAL = 113;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 114;
  /** RegularExpression Id. */
  int FLOAT = 115;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 116;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 117;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 118;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 119;
  /** RegularExpression Id. */
  int STRING = 120;
  /** RegularExpression Id. */
  int UNIQUE_STRING = 121;
  /** RegularExpression Id. */
  int RAW_STRING = 126;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTIPLE_LINE_COMMENT_STATE = 1;
  /** Lexical state. */
  int SINGLE_LINE_COMMENT_STATE = 2;
  /** Lexical state. */
  int RAW_STRING_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "\"\\n\"",
    "<token of kind 10>",
    "\"function\"",
    "\"class\"",
    "\"module\"",
    "\"interface\"",
    "\"extends\"",
    "\"involves\"",
    "\"joints\"",
    "\"personal\"",
    "\"relative\"",
    "\"everyone\"",
    "\"get\"",
    "\"set\"",
    "\"gest\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"for\"",
    "\"in\"",
    "\"switch\"",
    "\"when\"",
    "\"cast\"",
    "\"iterator\"",
    "\"super\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"block\"",
    "\"self\"",
    "\"with\"",
    "\"without\"",
    "\"order\"",
    "\"serve\"",
    "\"ignore\"",
    "\"groan\"",
    "\"true\"",
    "\"false\"",
    "\"nil\"",
    "\"alias\"",
    "\"retry\"",
    "\"redo\"",
    "\"goto\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"~=\"",
    "\"^=\"",
    "\">>\"",
    "\"<<\"",
    "\">>>\"",
    "\"<<<\"",
    "\">>=\"",
    "\"<<=\"",
    "\">>>=\"",
    "\"<<<=\"",
    "\"=>\"",
    "\"::\"",
    "\"#\"",
    "\":\"",
    "<CONSTANCE>",
    "<LOCALVARIABLE>",
    "<GLOBALVARIABLE>",
    "<INSTANCEVARIABLE>",
    "<CLASSVARIABLE>",
    "<UPPERLETTER>",
    "<DOWNERLETTER>",
    "<LETTER>",
    "<DIGIT>",
    "<LEAGLELETTER>",
    "<INTEGER>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<STRING>",
    "<UNIQUE_STRING>",
    "\"@\\\"\"",
    "\"\\\"\\\"\"",
    "\"\\n\"",
    "<token of kind 125>",
    "\"\\\"\"",
  };

}
