/* IrisParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. IrisParserTokenManager.java */
package com.irisine.jiris.compiler.parser;
import com.irisine.jiris.compiler.*;
import com.irisine.jiris.compiler.assistpart.*;
import com.irisine.jiris.compiler.expression.*;
import com.irisine.jiris.compiler.statement.*;
import java.io.File;
import java.io.FileInputStream;
import java.util.LinkedList;
import org.apache.commons.lang3.StringEscapeUtils;

/** Token Manager. */
@SuppressWarnings("unused")public class IrisParserTokenManager implements IrisParserConstants {
   String m_subStr = null;
   IrisIdentifier m_tmpIdentifier = null;
   IrisExpression m_tmpExpression = null;

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_2(){
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 9);
      default :
         return 1;
   }
}
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffff800L) != 0L)
         {
            jjmatchedKind = 102;
            return 3;
         }
         if ((active0 & 0x10000000000000L) != 0L)
            return 15;
         if ((active1 & 0x400000000000000L) != 0L)
            return 8;
         return -1;
      case 1:
         if ((active0 & 0xfffffeefeb800L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 1;
            }
            return 3;
         }
         if ((active0 & 0x11014000L) != 0L)
            return 3;
         return -1;
      case 2:
         if ((active0 & 0x800008600000L) != 0L)
            return 3;
         if ((active0 & 0xf7fffe69ff800L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 2;
            }
            return 3;
         }
         return -1;
      case 3:
         if ((active0 & 0xc21c0c6800000L) != 0L)
            return 3;
         if ((active0 & 0x35e3f201ff800L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 102;
               jjmatchedPos = 3;
            }
            return 3;
         }
         return -1;
      case 4:
         if ((active0 & 0x3562600001000L) != 0L)
            return 3;
         if ((active0 & 0x919241fe800L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 4;
            return 3;
         }
         return -1;
      case 5:
         if ((active0 & 0x81024022000L) != 0L)
            return 3;
         if ((active0 & 0x109001dc800L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 5;
            return 3;
         }
         return -1;
      case 6:
         if ((active0 & 0x9001d4800L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 6;
            return 3;
         }
         if ((active0 & 0x10000008000L) != 0L)
            return 3;
         return -1;
      case 7:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 7;
            return 3;
         }
         if ((active0 & 0x9001d0800L) != 0L)
            return 3;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 63;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4L);
      case 35:
         return jjStopAtPos(0, 99);
      case 37:
         jjmatchedKind = 75;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000L);
      case 38:
         jjmatchedKind = 77;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x400000L);
      case 40:
         return jjStopAtPos(0, 53);
      case 41:
         return jjStopAtPos(0, 54);
      case 42:
         jjmatchedKind = 73;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x81000L);
      case 43:
         jjmatchedKind = 71;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000L);
      case 44:
         return jjStopAtPos(0, 60);
      case 45:
         jjmatchedKind = 72;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000L);
      case 46:
         return jjStartNfaWithStates_0(0, 52, 15);
      case 47:
         jjmatchedKind = 74;
         return jjMoveStringLiteralDfa1_0(0xc0L, 0x100000L);
      case 58:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000L);
      case 59:
         return jjStopAtPos(0, 59);
      case 60:
         jjmatchedKind = 69;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x154000040L);
      case 61:
         jjmatchedKind = 64;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000002L);
      case 62:
         jjmatchedKind = 67;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xaa000010L);
      case 64:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000000000L);
      case 91:
         return jjStopAtPos(0, 57);
      case 93:
         return jjStopAtPos(0, 58);
      case 94:
         jjmatchedKind = 79;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2400000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x880001000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x6108000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x400008000800L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x8100000a00000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x80111014000L, 0x0L);
      case 106:
         return jjMoveStringLiteralDfa1_0(0x20000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x6001000080000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x44220400000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x200000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x18040000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 55);
      case 124:
         jjmatchedKind = 78;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 56);
      case 126:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 122);
         break;
      case 38:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(1, 61);
         break;
      case 42:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(1, 6);
         else if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(1, 76);
         break;
      case 47:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      case 58:
         if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         break;
      case 60:
         if ((active1 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x150000000L);
      case 61:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         else if ((active1 & 0x20000L) != 0L)
            return jjStopAtPos(1, 81);
         else if ((active1 & 0x40000L) != 0L)
            return jjStopAtPos(1, 82);
         else if ((active1 & 0x80000L) != 0L)
            return jjStopAtPos(1, 83);
         else if ((active1 & 0x100000L) != 0L)
            return jjStopAtPos(1, 84);
         else if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(1, 85);
         else if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(1, 86);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 88);
         break;
      case 62:
         if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 97);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xa8000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x400080000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x6045000ec0000L, active1, 0L);
      case 102:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(1, 24, 3);
         break;
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x818000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x1002006001000L, active1, 0L);
      case 110:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x14000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000808022000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x320400000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000800L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L, active1, 0L);
      case 124:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 60:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000L);
      case 61:
         if ((active1 & 0x20000000L) != 0L)
            return jjStopAtPos(2, 93);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 94);
         break;
      case 62:
         if ((active1 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 91;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x4020000002000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x540100000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000020020000L, active1, 0L);
      case 108:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0x404000080000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x80800000800L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x102000000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L, active1, 0L);
      case 114:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 27, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000040000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x86800000L, active1, 0L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 21, 3);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 3);
         return jjMoveStringLiteralDfa3_0(active0, 0xa01900000c000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(3, 95);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStopAtPos(3, 96);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x1100400080000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000800L, active1, 0L);
      case 101:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x2020400c000L, active1, 0L);
      case 102:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 38, 3);
         break;
      case 104:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L, active1, 0L);
      case 111:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 3);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 51, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000010000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000100100000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000041000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 3);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 31, 3);
         return jjMoveStringLiteralDfa4_0(active0, 0x820000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000002000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 3);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 3);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x804000000L);
      case 107:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 3);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 3);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x12000L);
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 44, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000040000L);
      case 114:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 33, 3);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 41, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x81000004000L);
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 3);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 48, 3);
         break;
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0xa0800L);
      case 121:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 3);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 3);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 3);
         break;
      case 102:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 3);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 104:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 3);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x80800L);
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 3);
         return jjMoveStringLiteralDfa6_0(active0, 0x800040000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 3);
         break;
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x44000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000800L);
      case 115:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 3);
         break;
      case 116:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 3);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L);
      case 118:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 3);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 3);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(7, 35, 3);
         break;
      case 108:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 18, 3);
         break;
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 3);
         break;
      case 114:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 32, 3);
         break;
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(8, 14, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 69;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 115)
                        kind = 115;
                     { jjCheckNAddStates(0, 5); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAddStates(6, 8); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(9, 11); }
                  else if (curChar == 46)
                     { jjCheckNAdd(15); }
                  else if (curChar == 36)
                     { jjCheckNAdd(5); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 111)
                        kind = 111;
                     { jjCheckNAddTwoStates(12, 13); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 111)
                        kind = 111;
                     { jjCheckNAddStates(12, 16); }
                  }
                  break;
               case 8:
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 104)
                     kind = 104;
                  { jjCheckNAdd(7); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 101)
                     kind = 101;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 4:
                  if (curChar == 36)
                     { jjCheckNAdd(5); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  { jjCheckNAdd(5); }
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 105)
                     kind = 105;
                  jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 14:
                  if (curChar == 46)
                     { jjCheckNAdd(15); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAddTwoStates(15, 16); }
                  break;
               case 17:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(18); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(18); }
                  break;
               case 19:
                  if (curChar == 34)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 20:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 22:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 23:
                  if (curChar == 34 && kind > 120)
                     kind = 120;
                  break;
               case 24:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(17, 20); }
                  break;
               case 25:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 26:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(25); }
                  break;
               case 28:
                  if (curChar == 39)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 29:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 31:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 32:
                  if (curChar == 39 && kind > 121)
                     kind = 121;
                  break;
               case 33:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 34:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 35:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0xff000000000000L & l) != 0L)
                     { jjCheckNAdd(34); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAddStates(0, 5); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAddTwoStates(38, 39); }
                  break;
               case 40:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(41); }
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(41); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(42, 43); }
                  break;
               case 44:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(45); }
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 47:
                  if (curChar != 46)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 50:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(51); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(51); }
                  break;
               case 52:
                  if (curChar != 48)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddStates(12, 16); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddTwoStates(54, 13); }
                  break;
               case 55:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddTwoStates(55, 13); }
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjAddStates(25, 26); }
                  break;
               case 58:
                  if (curChar == 46)
                     { jjCheckNAdd(59); }
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(59, 60); }
                  break;
               case 61:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(62); }
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(62); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 65:
                  if (curChar == 46)
                     { jjCheckNAdd(66); }
                  break;
               case 67:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(68); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 115)
                     kind = 115;
                  { jjCheckNAdd(68); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe80000000L & l) != 0L)
                  {
                     if (kind > 102)
                        kind = 102;
                     { jjCheckNAdd(3); }
                  }
                  else if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 101)
                        kind = 101;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 8;
                  if (curChar == 64)
                     { jjCheckNAdd(7); }
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 104)
                        kind = 104;
                     { jjCheckNAdd(7); }
                  }
                  else if (curChar == 64)
                     { jjCheckNAdd(9); }
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 101)
                     kind = 101;
                  { jjCheckNAdd(1); }
                  break;
               case 2:
                  if ((0x7fffffe80000000L & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  { jjCheckNAdd(3); }
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  { jjCheckNAdd(3); }
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 6:
                  if (curChar == 64)
                     { jjCheckNAdd(7); }
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 104)
                     kind = 104;
                  { jjCheckNAdd(7); }
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 105)
                     kind = 105;
                  { jjCheckNAdd(9); }
                  break;
               case 10:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 13:
                  if ((0x100000001000L & l) != 0L && kind > 111)
                     kind = 111;
                  break;
               case 16:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(30, 31); }
                  break;
               case 20:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 21:
                  if (curChar == 92)
                     { jjAddStates(32, 34); }
                  break;
               case 22:
                  if ((0x14404410000000L & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 29:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 30:
                  if (curChar == 92)
                     { jjAddStates(35, 37); }
                  break;
               case 31:
                  if ((0x14404410000000L & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 39:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(38, 39); }
                  break;
               case 43:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(40, 41); }
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(42, 43); }
                  break;
               case 53:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(54); }
                  break;
               case 54:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 111)
                     kind = 111;
                  { jjCheckNAddTwoStates(54, 13); }
                  break;
               case 56:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 57:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjAddStates(44, 45); }
                  break;
               case 60:
                  if ((0x1000000010000L & l) != 0L)
                     { jjAddStates(46, 47); }
                  break;
               case 63:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(64); }
                  break;
               case 64:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 66:
                  if ((0x1000000010000L & l) != 0L)
                     { jjAddStates(48, 49); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 20:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(9, 11); }
                  break;
               case 29:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(6, 8); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 69 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjStopStringLiteralDfa_3(int pos, long active0, long active1){
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_3(int pos, long active0, long active1){
   return jjMoveNfa_3(jjStopStringLiteralDfa_3(pos, active0, active1), pos + 1);
}
private int jjMoveStringLiteralDfa0_3(){
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 124);
      case 34:
         jjmatchedKind = 126;
         return jjMoveStringLiteralDfa1_3(0x800000000000000L);
      default :
         return jjMoveNfa_3(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_3(long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_3(0, 0L, active1);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active1 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 123);
         break;
      default :
         break;
   }
   return jjStartNfa_3(0, 0L, active1);
}
private int jjMoveNfa_3(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     kind = 125;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  kind = 125;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 125)
                     kind = 125;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_1(0x100L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(1, 8);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   38, 39, 42, 43, 46, 47, 29, 30, 32, 20, 21, 23, 53, 55, 13, 56, 
   63, 20, 21, 25, 23, 29, 30, 34, 32, 57, 58, 64, 65, 66, 17, 18, 
   22, 24, 26, 31, 33, 35, 40, 41, 44, 45, 50, 51, 59, 60, 61, 62, 
   67, 68, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, 
"\146\165\156\143\164\151\157\156", "\143\154\141\163\163", "\155\157\144\165\154\145", 
"\151\156\164\145\162\146\141\143\145", "\145\170\164\145\156\144\163", "\151\156\166\157\154\166\145\163", 
"\152\157\151\156\164\163", "\160\145\162\163\157\156\141\154", "\162\145\154\141\164\151\166\145", 
"\145\166\145\162\171\157\156\145", "\147\145\164", "\163\145\164", "\147\145\163\164", "\151\146", 
"\145\154\163\145", "\145\154\163\145\151\146", "\146\157\162", "\151\156", 
"\163\167\151\164\143\150", "\167\150\145\156", "\143\141\163\164", "\151\164\145\162\141\164\157\162", 
"\163\165\160\145\162", "\142\162\145\141\153", "\143\157\156\164\151\156\165\145", 
"\162\145\164\165\162\156", "\142\154\157\143\153", "\163\145\154\146", "\167\151\164\150", 
"\167\151\164\150\157\165\164", "\157\162\144\145\162", "\163\145\162\166\145", "\151\147\156\157\162\145", 
"\147\162\157\141\156", "\164\162\165\145", "\146\141\154\163\145", "\156\151\154", 
"\141\154\151\141\163", "\162\145\164\162\171", "\162\145\144\157", "\147\157\164\157", "\56", "\50", 
"\51", "\173", "\175", "\133", "\135", "\73", "\54", "\46\46", "\174\174", "\41", 
"\75", "\75\75", "\41\75", "\76", "\76\75", "\74", "\74\75", "\53", "\55", "\52", 
"\57", "\45", "\52\52", "\46", "\174", "\136", "\176", "\53\75", "\55\75", "\52\75", 
"\57\75", "\45\75", "\46\75", "\176\75", "\136\75", "\76\76", "\74\74", "\76\76\76", 
"\74\74\74", "\76\76\75", "\74\74\75", "\76\76\76\75", "\74\74\74\75", "\75\76", "\72\72", 
"\43", "\72", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = IrisToken.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 10)
         {
            jjmatchedKind = 10;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 10)
         {
            jjmatchedKind = 10;
         }
         break;
       case 3:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_3();
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        MoreLexicalActions();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      case 122 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                image.deleteCharAt(0); image.deleteCharAt(0);
         break;
      case 123 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                 image.deleteCharAt(image.length() - 1);
         break;
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 101 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          m_tmpIdentifier = new IrisIdentifier(IrisIdentifier.IdentifierType.Constance, matchedToken.image);
          m_tmpIdentifier.setLineNumber(matchedToken.beginLine);
          ((IrisToken)matchedToken).setSyntaxUnit(m_tmpIdentifier);
         break;
      case 102 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          m_tmpIdentifier = new IrisIdentifier(IrisIdentifier.IdentifierType.LocalVariable, matchedToken.image);
          m_tmpIdentifier.setLineNumber(matchedToken.beginLine);
          ((IrisToken)matchedToken).setSyntaxUnit(m_tmpIdentifier);
         break;
      case 103 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          m_tmpIdentifier = new IrisIdentifier(IrisIdentifier.IdentifierType.GlobalVariable, matchedToken.image);
          m_tmpIdentifier.setLineNumber(matchedToken.beginLine);
          ((IrisToken)matchedToken).setSyntaxUnit(m_tmpIdentifier);
         break;
      case 104 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          m_tmpIdentifier = new IrisIdentifier(IrisIdentifier.IdentifierType.InstanceVariable, matchedToken.image);
          m_tmpIdentifier.setLineNumber(matchedToken.beginLine);
          ((IrisToken)matchedToken).setSyntaxUnit(m_tmpIdentifier);
         break;
      case 105 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          m_tmpIdentifier = new IrisIdentifier(IrisIdentifier.IdentifierType.ClassVariable, matchedToken.image);
          m_tmpIdentifier.setLineNumber(matchedToken.beginLine);
          ((IrisToken)matchedToken).setSyntaxUnit(m_tmpIdentifier);
         break;
      case 111 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    m_tmpExpression = new IrisNativeObjectExpression(Integer.parseInt(matchedToken.image));
    m_tmpExpression.setLineNumber(matchedToken.beginLine);
    ((IrisToken)matchedToken).setSyntaxUnit(m_tmpExpression);
         break;
      case 115 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    m_tmpExpression = new IrisNativeObjectExpression(Double.parseDouble(matchedToken.image));
    m_tmpExpression.setLineNumber(matchedToken.beginLine);
    ((IrisToken)matchedToken).setSyntaxUnit(m_tmpExpression);
         break;
      case 120 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    m_subStr = StringEscapeUtils.unescapeJava(matchedToken.image.substring(1, matchedToken.image.length() - 1));
    m_tmpExpression = new IrisNativeObjectExpression(IrisNativeObjectExpression.NativeObjectType.String, m_subStr);
    m_tmpExpression.setLineNumber(matchedToken.beginLine);
    ((IrisToken)matchedToken).setSyntaxUnit(m_tmpExpression);
         break;
      case 121 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    m_subStr = StringEscapeUtils.unescapeJava(matchedToken.image.substring(1, matchedToken.image.length() - 1));
    m_tmpExpression = new IrisNativeObjectExpression(IrisNativeObjectExpression.NativeObjectType.UniqueString, m_subStr);
    m_tmpExpression.setLineNumber(matchedToken.beginLine);
    ((IrisToken)matchedToken).setSyntaxUnit(m_tmpExpression);
         break;
      case 126 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          image.deleteCharAt(image.length() - 1);
          matchedToken.image = image.toString();
      m_tmpExpression = new IrisNativeObjectExpression(IrisNativeObjectExpression.NativeObjectType.String, matchedToken.image);
      m_tmpExpression.setLineNumber(matchedToken.beginLine);
      ((IrisToken)matchedToken).setSyntaxUnit(m_tmpExpression);
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public IrisParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public IrisParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 69; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 4 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "MULTIPLE_LINE_COMMENT_STATE",
   "SINGLE_LINE_COMMENT_STATE",
   "RAW_STRING_STATE",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 1, 2, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, 
   -1, 0, 
};
static final long[] jjtoToken = {
   0xfffffffffffff801L, 0x430883ffffffffffL, 
};
static final long[] jjtoSkip = {
   0x33eL, 0x0L, 
};
static final long[] jjtoMore = {
   0x4c0L, 0x3c00000000000000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[69];
    private final int[] jjstateSet = new int[2 * 69];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    
    protected char curChar;
}
